matrix:
  include:
    - language: node_js
      node_js:
        - '6'
      install:
        - npm install -g markdownlint-cli
      script:
        - markdownlint *.md

    - language: generic
      notifications:
        email: false
      services:
        - docker
      before_install:
        - docker pull antidotelabs/syringe:latest
        - docker run -v $(pwd):/antidote antidotelabs/syringe syrctl validate /antidote
      install:
        - ./check-changelog.sh
      sudo: false