matrix:
  include:
    - language: node_js
      node_js:
        - '12'
      install:
        - npm install -g markdownlint-cli
        - npm install yaspeller-ci --save-dev
        - npm install -g write-good
      script:
        - yaspeller-ci lessons/**/*.md || true
        - markdownlint lessons/**/*.md || true
        - write-good `find ./lessons` *.md --no-tooWordy --parse || true
    
    - language: generic
      notifications:
        email: false
      services:
        - docker
      before_install:
        - docker pull antidotelabs/syringe:latest
        - docker run -v $(pwd):/antidote antidotelabs/syringe syrctl validate /antidote
      install:
        - ./check-changelog.sh
      sudo: false