---
- name: Custom CLI
  hosts: all
  gather_facts: no
  vars:
    ansible_user: antidote
    ansible_password: antidotepassword
  tasks:

    - name: Install prereqs
      pip: 
        requirements: /antidote/cli-emulator/requirements.txt
        extra_args: --user
    - name: Create bash_profile if it does not exist
      file: state=touch path=/home/antidote/.bash_profile
    - name: Add custom shell to bash_profile
      blockinfile:
        dest: "/home/antidote/.bash_profile"
        content: |
          exec /antidote/cli-emulator/cli_emulator.py